apiVersion: batch/v1
kind: Job
metadata:
  name: bsc-pf-job
spec:
  template:
    spec:
      containers:
      - name: bsc-pf-job
        image: yash5090/bsc-pf:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
